version: '3'
services:

  midi_meta_db:
    container_name: midi_meta_db
    image: postgres:16.2
    environment:
      PGUSER: pguser
      POSTGRES_USER: midiuser
      POSTGRES_PASSWORD: midipass
      POSTGRES_DB: midi_meta_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "midi_meta_db", "-U", "pguser" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - midinetwork

  midi_blob_db:
    container_name: midi_blob_db
    image: postgres:16.2
    environment:
      PGUSER: pguser
      POSTGRES_USER: blobuser
      POSTGRES_PASSWORD: blobpass
      POSTGRES_DB: midi_blob_db
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "midi_blob_db", "-U", "pguser" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - midinetwork

  midi_user_db:
    container_name: midi_user_db
    image: postgres:16.2
    environment:
      PGUSER: pguser
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: midi_user_db
    ports:
      - "5434:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "midi_user_db", "-U", "pguser" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - midinetwork

  user-service:
    container_name: user-service
    image: ghcr.io/n-sankell/examensarbete-ns-java22/user-service:master
    ports:
      - "8081:8081"
    environment:
      USER_DB_NAME: "midi_user_db"
      USER_DB_URL: "172.22.0.1"
    depends_on:
      midi_user_db:
        condition: service_healthy
    networks:
      - midinetwork

  midi-manager:
    container_name: midi-manager
    image: ghcr.io/n-sankell/examensarbete-ns-java22/midi-manager:master
    ports:
      - "8082:8082"
    environment:
      META_DB_NAME: "midi_meta_db"
      META_DB_URL: "172.22.0.1"
      BLOB_DB_NAME: "midi_blob_db"
      BLOB_DB_URL: "172.22.0.1"
    depends_on:
      midi_blob_db:
        condition: service_healthy
      midi_meta_db:
        condition: service_healthy
    networks:
      - midinetwork

  react-app:
    container_name: react-app
    image: ghcr.io/n-sankell/examensarbete-ns-java22/react-app:master
    ports:
      - "3000:3000"
    networks:
      - midinetwork

networks:
  midinetwork:
    driver: bridge