version: '3'
services:

  react-app:
    container_name: react-app
    build:
      dockerfile: Dockerfile
      args:
        - MIDI_ADDRESS=localhost:8082
        - USER_ADDRESS=localhost:8081
    image: ex-react-app:test
    ports:
      - "3000:3000"

  user-service:
    container_name: user-service
    build:
      dockerfile: Dockerfile
      context: ./user-service
    image: ex-user-service:test
    ports:
      - "8081:8081"
    environment:
      USER_DB_NAME: "midi_user_db"
    #depends_on:
    #  mysql:
    #    condition: service_healthy

  midi-manager:
    container_name: midi-manager
    build:
      dockerfile: Dockerfile
      context: ./midi-manager
    image: ex-midi-manager
    ports:
      - "8082:8082"
    environment:
      META_DB_NAME: "midi_meta_db"
      BLOB_DB_NAME: "midi_blob_db"
    #depends_on:
    #  mysql:
    #    condition: service_healthy