apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        docker.pkg.github.com/n-sankell/examensarbete-ns-java22/user-service:latest
        ports:
        - containerPort: 8081
        
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: USER_DB_PORT
          value: "5431"

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: user-db-postgres-user
              
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: user-db-postgres-password

        - name: USER_DB_NAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: user-db-postgres-db
              
        - name: USER_DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: user-db-url

        - name: ALLOWED_ORIGIN
          value: http://127.0.0.1:51678

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: jwt-key

---

apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31000
