spring:
  main:
    banner-mode: off

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog-user.yaml
    default-schema: public

  datasource:
    user:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://${META_DB_URL:localhost}:${META_DB_PORT:5434}/${META_DB_NAME:midi_user_db}?gssEncMode=disable&useSSL=false
      username: ${DB_USER:dbuser}
      password: ${DB_PASSWORD:dbpass}

  sql:
    init:
      mode: never

allowed:
  origin: ${ALLOWED_ORIGIN:http://localhost:3000}

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: ${JWT_EXP:86400000}