name: Build and Push React App Docker Image

on:
  push:
    #branches:
    #  - master
    paths:
      - react-app/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: n-sankell/examensarbete-ns-java22/react-app

jobs:
  build-and-push-react-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
  
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      env:
        MIDI_ADDRESS: localhost:8082
        USER_ADDRESS: localhost:8081
    outputs:
      image: ${{steps.meta.outputs.tags}}
      tags: ${{steps.build-and-push-docker-image.outputs.tags}}
      
  deploy-react-app:
    needs: build-and-push-react-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull ghcr.io/n-sankell/examensarbete-ns-java22/react-app:${{needs.build-and-push-react-app.outputs.image}}

      - name: Update Docker Compose file
        run: |
          cd $GITHUB_WORKSPACE
          sed -i "s|IMAGE_NAME:.*|IMAGE_NAME: ghcr.io/n-sankell/examensarbete-ns-java22/react-app:master|g" docker-compose.deploy.yaml

      - name: Restart Docker services
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up -d