name: Build and Push Midi Manager Image

on:
  push:
    branches:
      - master
    paths:
      - midi-manager/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: n-sankell/examensarbete-ns-java22/midi-manager

jobs:
  build-and-push-midi-manager:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
  
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: ./midi-manager
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      image: ${{steps.meta.outputs.tags}}
      tags: ${{steps.build-and-push-docker-image.outputs.tags}}

  deploy_simulation:
    needs: build-and-push-midi-manager
    runs-on: ubuntu-latest
    steps:

    - name: Echo Image Name
      run: |
        echo "Deploying image: ${{needs.build-and-push-image.outputs.image}}"
