name: Build and Push Docker Images

on:
  push:
    branches:
      - dev-workflow-image-build
    paths:
      - react-app/**

jobs:
  build-and-push-react-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push User Service Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./react-app
        push: true
        tags: n-sankell/examensarbete-ns-java22/react-app:latest
