name: Build and Push Docker Images

on:
  push:
    branches:
      - dev-workflow-image-build
    paths:
      - user-service/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push user-service Docker image
        run: |
          cd user-service
          docker build -t docker.pkg.github.com/n-sankell/examensarbete-ns-java22/user-service:latest .
          docker push docker.pkg.github.com/n-sankell/examensarbete-ns-java22/user-service:latest
