name: Build And Test User-Service On Push

on:
  push:
    paths:
      - user-service/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-test-check-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache User-Service Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~./user-service/gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make User-Service Gradle Executable
      run: chmod +x ./gradlew
      working-directory: user-service

    - name: Generate User-Service OpenAPI Sources
      run: ./gradlew openApiGenerate
      working-directory: user-service

    - name: Run User-Service Tests
      run: ./gradlew test
      working-directory: user-service
