openapi: 3.0.3
info:
  title: Midi API
  version: 1.0.0

paths:

  /midis/create:
    post:
      summary: Create a new midi entry
      description: "Create a new midi entry, with meta and binary data."
      operationId: createMidi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MidiCreateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MidiWithData'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Midi

  /midis/public:
    get:
      summary: Get all public midis
      description: "Returns a list of public midis."
      operationId: getPublicMidis
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Midis'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Midi

  /midis/user/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      summary: Get all midis from a user
      description: "Returns a list of midis that belongs to the provided userId"
      operationId: getUserMidis
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Midis'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Midi

  /midis/midi/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      summary: Edit a midi item
      description: "Edit a midi item in the database."
      operationId: editMidi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MidiEditRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MidiWithData'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Midi

    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      summary: Delete a midi item
      description: "Deletes metadata and binary midi data from the database."
      operationId: deleteMidi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Midi

    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      summary: Get midi by blobId
      description: "Get a midi with meta and binary data from the database by blobId."
      operationId: getMidi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MidiWithData'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Midi

  /midis/meta/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      summary: Edit midi metadata
      description: "Edit the metadata for a midi entry."
      operationId: editMidiMeta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MidiEditMetaRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MidiWithData'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Midi

  /midis/binary/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      summary: Edit midi binary data
      description: "Edit the binary data for a midi."
      operationId: editMidiBinary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MidiEditBinaryRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MidiWithData'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Midi

components:
  schemas:

    MidiCreateRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          description: "User ID associated with the MIDI"
        isPrivate:
          type: boolean
          description: "Flag indicating if the MIDI is private"
        filename:
          type: string
          description: "Filename of the MIDI"
        artist:
          type: string
          description: "Artist of the MIDI"
        title:
          type: string
          description: "Title of the MIDI"
        midiFile:
          type: string
          description: "MIDI file in binary format (Base64)"
      required:
        - userId
        - filename
        - midiFile

    MidiEditRequest:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/MidiEditMetaRequest'
        binaryData:
          $ref: '#/components/schemas/MidiEditBinaryRequest'
      required:
        - metadata
        - binaryData

    MidiEditBinaryRequest:
      type: object
      properties:
        midiFile:
          type: string
          description: "MIDI file in binary format (Base64)"
      required:
        - filename

    MidiEditMetaRequest:
      type: object
      properties:
        isPrivate:
          type: boolean
          description: "Flag indicating if the MIDI is private"
        filename:
          type: string
          description: "Filename of the MIDI"
        artist:
          type: string
          description: "Artist of the MIDI"
        title:
          type: string
          description: "Title of the MIDI"
      required:
        - filename

    Midi:
      type: object
      properties:
        midiId:
          type: string
          format: uuid
          description: "Unique identifier for the MIDI"
        blobRef:
          type: string
          format: uuid
          description: "Reference to the blob"
        userRef:
          type: string
          format: uuid
          description: "Reference to the user"
        isPrivate:
          type: boolean
          description: "Flag indicating if the MIDI is private"
        filename:
          type: string
          description: "Filename of the MIDI"
        artist:
          type: string
          description: "Artist of the MIDI"
        title:
          type: string
          description: "Title of the MIDI"
        dateCreated:
          type: string
          format: date-time
          description: "Timestamp of creation"
        dateEdited:
          type: string
          format: date-time
          description: "Timestamp of last edit"
      required:
        - midiId
        - filename
        - dateCreated
        - dateEdited

    BinaryData:
      type: object
      properties:
        binaryId:
          type: string
          format: uuid
          description: "UUID associated with the MIDI"
        midiFile:
          type: string
          description: "MIDI file in binary format"
      required:
        - midiId
        - midiFile

    MidiWithData:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/Midi'
        binary:
          $ref: '#/components/schemas/BinaryData'

    Midis:
      type: object
      properties:
        midis:
          type: array
          items:
            $ref: '#/components/schemas/Midi'

    EmptyResponse:
      type: object
      properties: { }

  responses:
    NotFound:
      description: The specified resource was not found
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden (jwt was valid, but user was not found)
    Conflict:
      description: Conflict e.g. data violates a constraint such as unique email addresses
    BadRequest:
      description: Bad Request - an issue with request data
    InternalServerError:
      description: Internal Server Error - a generic 'something bad' that we couldn't recover from happened

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]

servers:
  - url: http://{address}
    variables:
      address:
        default: localhost:8080
        description: The current environment
